"""Initial migration

Revision ID: 4f26aff565b5
Revises: 
Create Date: 2024-07-23 10:34:44.117180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f26aff565b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('headshot', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('resume', sa.String(length=1000), nullable=True),
    sa.Column('requirements', sa.String(length=4000), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.String(length=4000), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.Column('job_offer', sa.Boolean(), nullable=True),
    sa.Column('rejection', sa.Boolean(), nullable=True),
    sa.Column('interviewing', sa.Boolean(), nullable=True),
    sa.Column('accepted_offer', sa.Boolean(), nullable=True),
    sa.Column('ghosted', sa.Boolean(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('last_logged_task', sa.String(length=255), nullable=True),
    sa.Column('last_logged_task_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_table.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referral_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task_for_employee', sa.Integer(), nullable=True),
    sa.Column('task_for_recruiter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_employee'], ['employee_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_recruiter'], ['recruiter_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task_for_employee', sa.Integer(), nullable=True),
    sa.Column('task_for_recruiter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_employee'], ['employee_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_recruiter'], ['recruiter_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_task_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task_for_employee', sa.Integer(), nullable=True),
    sa.Column('task_for_recruiter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_employee'], ['employee_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_recruiter'], ['recruiter_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('next_step_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('task_for_employee', sa.Integer(), nullable=True),
    sa.Column('task_for_recruiter', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('step_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_employee'], ['employee_table.id'], ),
    sa.ForeignKeyConstraint(['task_for_recruiter'], ['recruiter_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('next_step_table')
    op.drop_table('general_task_table')
    op.drop_table('email_table')
    op.drop_table('call_table')
    op.drop_table('job_table')
    op.drop_table('recruiter_table')
    op.drop_table('employee_table')
    op.drop_table('users_table')
    op.drop_table('referral_table')
    op.drop_table('company_table')
    # ### end Alembic commands ###
